### ISSUE TITLE
DSN secret is deprecated, new format doesn't work however

### ISSUE THREAD

**Issue by bufke** [danielgek/nativescript-sentry#15]
Sentry has deprecated the secret part of the DSN. However this project errors without it

`TypeError: Cannot read property 'split' of undefined`

A work around is to add an `:` after key in the DSN. The new format was previously called the "public DSN" before the secret was removed.

Semi related to https://github.com/danielgek/nativescript-sentry/issues/5

It would probably be best to make the secret optional and update the readme example to not use secret. Happy to assist if necessary.

**Comment by kvnvelasco** [comment]
#17 addresses the issues with Android. If you have access to a MacOS dev environment, d'ywanna make it work for iOS?

**Comment by benjlin** [comment]
@kvnvelasco I spent a few minutes reading up on podfiles, and i am no expert but since there is no specified version to use for Sentry on iOS, at the build time of the implementing app for this plugin the newest available version should be used. (this is probably not best practice, but as i said i am no expert)

Since your pull request should update the android plugin and the iOS plugin should be upto date out of the box, everything should be good.

I just spent the last two hours trying to test this, but I could not get the demo-ng application provided to work kept throwing the below error no matter what i tried, ideas?

`Error: com.tns.NativeScriptException: Failed to find module: "nativescript-sentry", relative to: app/tns_modules/`

**Comment by kvnvelasco** [comment]
@benjlin Interestingly, I got the demo-ng working just fine. How did you run it? The `src` directory has a script for running the demo `npm run demo.ng.android`

**Comment by kvnvelasco** [comment]
re: Podfiles I think it's just a matter of updating `:tag => '3.9.1'` to `:tag => '4.1.0`. I don't have an iOS device or simulator to make sure that works though. 

https://github.com/getsentry/sentry-cocoa/releases

**Comment by benjlin** [comment]
@kvnvelasco I ran the project by navigating into demo-ng and running `tns run android` 
when I get home I will update the tag and give it a go and report back

**Comment by cendekia** [comment]
@benjlin Have you solved this issue? It happen to me too

**Comment by kevmorpain** [comment]
Hi, I have the same error using nativescript-vue. When will it be fixed?

**Comment by cendekia** [comment]
@kvnvelasco actually someone already did fix and submitted [PR#17](https://github.com/danielgek/nativescript-sentry/pull/17)

but @danielgek seem busy right now, for temporary maybe you can look at [my medium](https://medium.com/@cendekiapp/how-to-add-sentry-to-your-n-ativescript-app-60eb1a45bda8)

Hope it can help :)

**Comment by danielgek** [comment]
this is fixed in 1.6.1
