### ISSUE TITLE
Native errors are not tracked anymore

### ISSUE THREAD

**Issue by jeremypele** [danielgek/nativescript-sentry#9]
Since the update to 1.5.0, I've noticed that js issues are well tracked but there is no native issues raised anymore on sentry.

I've got a bunch of issues poppin on play.store but nothing on sentry anymore

**Comment by Burgov** [comment]
@jeremypele is this using angular and only on iOS? I found that by initializing the module in Angular, the AppDelegate is initialized too late

**Comment by jeremypele** [comment]
@Burgov yes it is! 👍

**Comment by Burgov** [comment]
I think it should be fixed by calling the non-angular init method in main(.aot).ts (while keeping the Module reference in the AppModule), but i'm having other issues with this plugin that block me from asserting that.

**Comment by jeremypele** [comment]
Thought about that too but keeping the non-angular initializer only for now. That's too bad cause we loose all the user and breadcrumbs infos :/

**Comment by bradmartin** [comment]
@jeremypele - I have a fork that removes the raven-js dep and utilizes just the android/ios sentry libs. I'd be curious if this helps your use case. There is some cleaning up I need to do on my fork to make sure it's retained functionality (or improved 😄). I'm going to try and add a ng demo app to my fork and see how that goes tonight.

**Comment by jeremypele** [comment]
@bradmartin Sounds good :)

**Comment by bradmartin** [comment]
@jeremypele - got my fork working with the native SDKs without raven, all works well except for one last issue which is the uncaught exception that logs for iOS.

If you want to take a read about my question to the NS team [here](https://github.com/NativeScript/NativeScript/issues/6136) it is 😄 hopefully it can be improved because I've ran into no issue with my fork since it doesn't have to rely on the raven-js portion of sentry and it seems to integrate better with NS 👍 fingers crossed a good solution can happen.

**Comment by danielgek** [comment]
released 1.6.1 that has @bradmartin working code, i'm trying to get the ios exeption working
